//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 04:48:15 PM IST 
//


package com.infoiv.orders;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infoiv.orders package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infoiv.orders
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteOrderDetailsRequest }
     * 
     */
    public DeleteOrderDetailsRequest createDeleteOrderDetailsRequest() {
        return new DeleteOrderDetailsRequest();
    }

    /**
     * Create an instance of {@link OrderDetailsResponse }
     * 
     */
    public OrderDetailsResponse createOrderDetailsResponse() {
        return new OrderDetailsResponse();
    }

    /**
     * Create an instance of {@link OrderDetails }
     * 
     */
    public OrderDetails createOrderDetails() {
        return new OrderDetails();
    }

    /**
     * Create an instance of {@link AllOrderDetailsRequest }
     * 
     */
    public AllOrderDetailsRequest createAllOrderDetailsRequest() {
        return new AllOrderDetailsRequest();
    }

    /**
     * Create an instance of {@link AllOrderDetailsResponse }
     * 
     */
    public AllOrderDetailsResponse createAllOrderDetailsResponse() {
        return new AllOrderDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteOrderDetailsResponse }
     * 
     */
    public DeleteOrderDetailsResponse createDeleteOrderDetailsResponse() {
        return new DeleteOrderDetailsResponse();
    }

    /**
     * Create an instance of {@link OrderDetailsRequest }
     * 
     */
    public OrderDetailsRequest createOrderDetailsRequest() {
        return new OrderDetailsRequest();
    }

}
