//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.02 at 04:48:15 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://infoiv.com/orders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.infoiv.orders;
